//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbit {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Accent {
            get {
                return ((string)(this["Accent"]));
            }
            set {
                this["Accent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomThemes {
            get {
                return ((string)(this["CustomThemes"]));
            }
            set {
                this["CustomThemes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomAccentColors {
            get {
                return ((string)(this["CustomAccentColors"]));
            }
            set {
                this["CustomAccentColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotReloadScriptPath {
            get {
                return ((string)(this["HotReloadScriptPath"]));
            }
            set {
                this["HotReloadScriptPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScriptProfiles {
            get {
                return ((string)(this["ScriptProfiles"]));
            }
            set {
                this["ScriptProfiles"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConsoleAutoScroll {
            get {
                return ((bool)(this["ConsoleAutoScroll"]));
            }
            set {
                this["ConsoleAutoScroll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double FloatingMenuLeft {
            get {
                return ((double)(this["FloatingMenuLeft"]));
            }
            set {
                this["FloatingMenuLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public double FloatingMenuTop {
            get {
                return ((double)(this["FloatingMenuTop"]));
            }
            set {
                this["FloatingMenuTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.95")]
        public double FloatingMenuOpacity {
            get {
                return ((double)(this["FloatingMenuOpacity"]));
            }
            set {
                this["FloatingMenuOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public string FloatingMenuDirection {
            get {
                return ((string)(this["FloatingMenuDirection"]));
            }
            set {
                this["FloatingMenuDirection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double FloatingMenuInactivitySeconds {
            get {
                return ((double)(this["FloatingMenuInactivitySeconds"]));
            }
            set {
                this["FloatingMenuInactivitySeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FloatingMenuAutoDirection {
            get {
                return ((bool)(this["FloatingMenuAutoDirection"]));
            }
            set {
                this["FloatingMenuAutoDirection"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double FloatingMenuBackgroundOpacity {
            get {
                return ((double)(this["FloatingMenuBackgroundOpacity"]));
            }
            set {
                this["FloatingMenuBackgroundOpacity"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoInjectOnReady {
            get {
                return ((bool)(this["AutoInjectOnReady"]));
            }
            set {
                this["AutoInjectOnReady"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenuAddSession {
            get {
                return ((bool)(this["ShowMenuAddSession"]));
            }
            set {
                this["ShowMenuAddSession"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenuInject {
            get {
                return ((bool)(this["ShowMenuInject"]));
            }
            set {
                this["ShowMenuInject"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenuSessions {
            get {
                return ((bool)(this["ShowMenuSessions"]));
            }
            set {
                this["ShowMenuSessions"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenuAccountManager {
            get {
                return ((bool)(this["ShowMenuAccountManager"]));
            }
            set {
                this["ShowMenuAccountManager"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenuScriptControls {
            get {
                return ((bool)(this["ShowMenuScriptControls"]));
            }
            set {
                this["ShowMenuScriptControls"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenuThemeManager {
            get {
                return ((bool)(this["ShowMenuThemeManager"]));
            }
            set {
                this["ShowMenuThemeManager"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenuConsole {
            get {
                return ((bool)(this["ShowMenuConsole"]));
            }
            set {
                this["ShowMenuConsole"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenuApiDocumentation {
            get {
                return ((bool)(this["ShowMenuApiDocumentation"]));
            }
            set {
                this["ShowMenuApiDocumentation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenuSettings {
            get {
                return ((bool)(this["ShowMenuSettings"]));
            }
            set {
                this["ShowMenuSettings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenuToolsOverview {
            get {
                return ((bool)(this["ShowMenuToolsOverview"]));
            }
            set {
                this["ShowMenuToolsOverview"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenuSessionGallery {
            get {
                return ((bool)(this["ShowMenuSessionGallery"]));
            }
            set {
                this["ShowMenuSessionGallery"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenuOrbitView {
            get {
                return ((bool)(this["ShowMenuOrbitView"]));
            }
            set {
                this["ShowMenuOrbitView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenuFsmNodeEditor {
            get {
                return ((bool)(this["ShowMenuFsmNodeEditor"]));
            }
            set {
                this["ShowMenuFsmNodeEditor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFloatingMenuOnSessionTabs {
            get {
                return ((bool)(this["ShowFloatingMenuOnSessionTabs"]));
            }
            set {
                this["ShowFloatingMenuOnSessionTabs"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowFloatingMenuOnToolTabs {
            get {
                return ((bool)(this["ShowFloatingMenuOnToolTabs"]));
            }
            set {
                this["ShowFloatingMenuOnToolTabs"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool ShowFloatingMenuOnHome {
			get {
				return ((bool)(this["ShowFloatingMenuOnHome"]));
			}
			set {
				this["ShowFloatingMenuOnHome"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("MiddleMouse")]
		public string FloatingMenuQuickToggle {
			get {
				return ((string)(this["FloatingMenuQuickToggle"]));
			}
			set {
				this["FloatingMenuQuickToggle"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("80")]
		public double FloatingMenuDockEdgeThreshold {
			get {
                return ((double)(this["FloatingMenuDockEdgeThreshold"]));
            }
            set {
                this["FloatingMenuDockEdgeThreshold"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public double FloatingMenuDockCornerThreshold {
            get {
                return ((double)(this["FloatingMenuDockCornerThreshold"]));
            }
            set {
                this["FloatingMenuDockCornerThreshold"] = value;
            }
        }
        
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0.55")]
		public double FloatingMenuDockCornerRoundness {
			get {
				return ((double)(this["FloatingMenuDockCornerRoundness"]));
			}
			set {
				this["FloatingMenuDockCornerRoundness"] = value;
			}
		}
        
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0.85")]
		public double FloatingMenuDockEdgeCoverage {
			get {
				return ((double)(this["FloatingMenuDockEdgeCoverage"]));
			}
			set {
				this["FloatingMenuDockEdgeCoverage"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0.32")]
		public double FloatingMenuDockZoneOpacity {
			get {
				return ((double)(this["FloatingMenuDockZoneOpacity"]));
			}
			set {
				this["FloatingMenuDockZoneOpacity"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("120")]
		public double FloatingMenuDockCornerHeight {
			get {
				return ((double)(this["FloatingMenuDockCornerHeight"]));
			}
			set {
				this["FloatingMenuDockCornerHeight"] = value;
			}
		}
		
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool FloatingMenuShowAllSnapZonesOnClip {
			get {
				return ((bool)(this["FloatingMenuShowAllSnapZonesOnClip"]));
			}
            set {
				this["FloatingMenuShowAllSnapZonesOnClip"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool ShowFloatingMenuAutoShow {
			get {
				return ((bool)(this["ShowFloatingMenuAutoShow"]));
			}
			set {
				this["ShowFloatingMenuAutoShow"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool ShowThemeManagerWelcomeMessage {
			get {
				return ((bool)(this["ShowThemeManagerWelcomeMessage"]));
			}
			set {
				this["ShowThemeManagerWelcomeMessage"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("2")]
		public int OrbitViewGridDensity {
			get {
				return ((int)(this["OrbitViewGridDensity"]));
			}
			set {
				this["OrbitViewGridDensity"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("OrbitView")]
		public string DefaultSessionView {
			get {
				return ((string)(this["DefaultSessionView"]));
			}
			set {
				this["DefaultSessionView"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("OrbitView")]
		public string SessionLaunchBehavior {
			get {
				return ((string)(this["SessionLaunchBehavior"]));
			}
			set {
				this["SessionLaunchBehavior"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("1")]
		public int OrbitViewCompactness {
			get {
				return ((int)(this["OrbitViewCompactness"]));
			}
			set {
				this["OrbitViewCompactness"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int SessionHeaderDensity {
			get {
				return ((int)(this["SessionHeaderDensity"]));
			}
			set {
				this["SessionHeaderDensity"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int OrbitHeaderDensity {
			get {
				return ((int)(this["OrbitHeaderDensity"]));
			}
			set {
				this["OrbitHeaderDensity"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int GalleryHeaderDensity {
			get {
				return ((int)(this["GalleryHeaderDensity"]));
			}
			set {
				this["GalleryHeaderDensity"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int SessionsHeaderDensity {
			get {
				return ((int)(this["SessionsHeaderDensity"]));
			}
			set {
				this["SessionsHeaderDensity"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("1")]
		public int OrbitViewTabHeaderSize {
			get {
				return ((int)(this["OrbitViewTabHeaderSize"]));
			}
			set {
				this["OrbitViewTabHeaderSize"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("2")]
		public int OrbitViewBorderThickness {
			get {
				return ((int)(this["OrbitViewBorderThickness"]));
			}
			set {
				this["OrbitViewBorderThickness"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool AutoOpenOrbitViewOnStartup {
			get {
				return ((bool)(this["AutoOpenOrbitViewOnStartup"]));
			}
			set {
				this["AutoOpenOrbitViewOnStartup"] = value;
			}
		}
	}
}
